defaults:
  - server: serenity
  
comet:
  project: BOEM
  workspace: bw4sz

check_annotations: true
# Force upload bypasses the pipeline, useful for debugging and starting a new project
force_upload: true
label_studio:
  project_name: "Bureau of Ocean Energy Management"
  url: "https://labelstudio.naturecast.org/"
  folder_name: "/pgsql/retrieverdash/everglades-label-studio/everglades-data"
  images_to_annotate_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27
  annotated_images_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27/annotated
  csv_dir: /blue/ewhite/b.weinstein/BOEM/annotations

predict:
  patch_size: 2000
  patch_overlap: 0
  min_score: 0.5

pipeline:
  confidence_threshold: 0.5
  limit_empty_frac: 0.1

propagate:
  time_threshold_seconds: 5
  distance_threshold_pixels: 50

detection_model:
  checkpoint: bird
  checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/detection/checkpoints
  validation_csv_path:
  train_csv_folder: /blue/ewhite/b.weinstein/BOEM/annotations/
  train_image_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27/annotated
  crop_image_dir: /blue/ewhite/b.weinstein/BOEM/detection/crops/
  limit_empty_frac: 0
  fast_dev_run: false
  labels:
    - "Bird"

classification_model:
  checkpoint: 
  checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
  validation_csv_path: 
  train_csv_folder: /blue/ewhite/b.weinstein/BOEM/annotations/
  train_image_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27/annotated
  crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/
  under_sample_ratio: 0
  fast_dev_run: True

pipeline_evaluation:
  detect_ground_truth_dir: 
  classify_confident_ground_truth_dir:
  classify_uncertain_ground_truth_dir:
  # This is an average mAP threshold for now, but we may want to add a per-iou threshold in the future
  detection_true_positive_threshold: 0.8
  detection_false_positive_threshold: 0.5
  classification_avg_score: 0.5
  image_dir:

reporting:
  image_dir: /blue/ewhite/b.weinstein/BOEM/reporting/samples
  report_dir: /blue/ewhite/b.weinstein/BOEM/reporting/reports
  metadata: /blue/ewhite/b.weinstein/BOEM/reporting/metadata.csv

active_learning:
  image_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27
  strategy: 'target-labels'
  n_images: 1
  patch_size: 2000
  patch_overlap: 0
  min_score: 0.2
  model_checkpoint:
  target_labels:
    - "Bird"
  
  # Optional parameters:
  evaluation: 
  dask_client: 
  pool_limit: 10
  gpus: 1

active_testing:
  image_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27
  strategy: 'random'
  n_images: 1
  m: 
  patch_size: 2000
  patch_overlap: 0
  min_score: 0.2

deepforest:
  train:
    fast_dev_run: True
    epochs: 1
  workers: 0
