defaults:
  - server: serenity

checkpoint: bird

comet:
  project: BOEM
  workspace: bw4sz

check_annotations: false
label_studio:
  project_name: "Bureau of Ocean Energy Management"
  url: "https://labelstudio.naturecast.org/"
  api_key: "${oc.env:LABEL_STUDIO_API_KEY}"
  folder_name: "/pgsql/retrieverdash/everglades-label-studio/everglades-data"

predict:
  patch_size: 450
  patch_overlap: 0
  min_score: 0.5

pipeline:
  confidence_threshold: 0.5
  limit_empty_frac: 0.1

propagate:
  time_threshold_seconds: 5
  distance_threshold_pixels: 50

detection_model:
  validation_csv_path:
  train_csv_folder:
  train_image_dir:
  crop_image_dir:
  limit_empty_frac: 0
  fast_dev_run: false
  checkpoint_dir:
  labels:
    - "Bird"

classification_model:
  validation_csv_path:
  train_csv_folder:
  under_sample_ratio: 0
  fast_dev_run: false

pipeline_evaluation:
  detect_ground_truth_dir:
  classify_confident_ground_truth_dir:
  classify_uncertain_ground_truth_dir:
  # This is an average mAP threshold for now, but we may want to add a per-iou threshold in the future
  detection_true_positive_threshold: 0.8
  detection_false_positive_threshold: 0.5
  classification_avg_score: 0.5
  image_dir:

reporting:
  report_dir:

active_learning:
  images_to_annotate_dir:
  strategy: 'random'
  n_images: 100
  m: 10
  patch_size: 256
  patch_overlap: 0.5
  min_score: 0.5
  model_checkpoint:
  target_labels:
  
  # Optional parameters:
  evaluation: null
  dask_client: null
  pool_limit: null

active_testing:
  images_to_annotate_dir:
  strategy: 'random'
  n_images: 100
  m: 10
  patch_size: 256
  patch_overlap: 0.5
  min_score: 0.5

deepforest:
  train:
    fast_dev_run: True
  workers: 0
