defaults:
  - server: serenity

checkpoint: bird

comet:
  project: BOEM
  workspace: bw4sz

check_annotations: false
label_studio:
  project_name: "Bureau of Ocean Energy Management"
  url: "https://labelstudio.naturecast.org/"
  api_key: "${oc.env:LABEL_STUDIO_API_KEY}"
  folder_name: "/pgsql/retrieverdash/everglades-label-studio/everglades-data"

pipeline:
  confidence_threshold: 0.5
  patch_size: 450
  patch_overlap: 0
  limit_empty_frac: 0.1

train:
  validation_csv_path:
  train_csv_folder:
  train_image_dir:
  crop_image_dir:
  under_sample_ratio: 0
  limit_empty_frac: 0
  fast_dev_run: false
  checkpoint_dir:
  labels:
    - "Bird"

pipeline_evaluation:
  detection_annotations_dir:
  classification_annotations_dir:
  detection_true_positive_threshold: 0.8
  detection_false_positive_threshold: 0.5
  classification_avg_score: 0.5
  target_labels:
    - "Bird"

choose_images:
  images_to_annotate_dir: '/path/to/images'
  strategy: 'some_strategy'
  n_images: 100
  m: 10
  patch_size: 256
  patch_overlap: 0.5
  min_score: 0.5
  model_checkpoint: '/path/to/model'
  target_labels:
    - 'label1'
    - 'label2'
  # Optional parameters:
  evaluation: null
  dask_client: null
  pool_limit: null

deepforest:
  train:
    fast_dev_run: True
