checkpoint: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/checkpoints/ec4851c1e15e44ae847210fbb69cd74c.ckpt
checkpoint_train_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/crops/train
checkpoint_num_classes: 40
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
train_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/train
val_crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/val
fast_dev_run: False
max_epochs: 10
lr: 0.00001
batch_size: 16
workers: 10
