checkpoint: 
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/classification/checkpoints
train_csv_folder: /blue/ewhite/b.weinstein/BOEM/annotations/train
train_image_dir: /blue/ewhite/b.weinstein/BOEM/sample_flight/JPG_2024_Jan27/annotated
crop_image_dir: /blue/ewhite/b.weinstein/BOEM/classification/crops/
under_sample_ratio: 0
trainer:
  fast_dev_run: False
  max_epochs: 10
  lr: 0.00001
  batch_size: 16
  workers: 10