checkpoint: 
checkpoint_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/checkpoints/
train_csv_folder: 
train_image_dir: /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/crops
crop_image_dir:  /blue/ewhite/b.weinstein/BOEM/UBFAI Images with Detection Data/classification/crops/
under_sample_ratio: 0
trainer:
  fast_dev_run: False
  max_epochs: 100
  lr: 0.00001
  batch_size: 16
  workers: 10
